import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CASE_STUDIES, CASE_STUDY_ORDER } from "@/lib/case-studies";
import type { CaseStudyId } from "@/lib/case-studies";
import { CaseStudyPageView } from "@/components/portfolio/case-study/case-study-page";

interface RouteParams {
  slug: string;
}

export function generateStaticParams(): RouteParams[] {
  return CASE_STUDY_ORDER.map((slug) => ({ slug }));
}

function resolveStudy(slug: string) {
  const id = slug as CaseStudyId;
  return CASE_STUDY_ORDER.includes(id) ? CASE_STUDIES[id] : null;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<RouteParams>;
}): Promise<Metadata> {
  const { slug } = await params;
  const study = resolveStudy(slug);
  if (!study) return {};

  const title = `${study.title} — ${study.subtitle} | Divyanshu Singh`;
  return {
    title,
    description: study.hero.paragraph,
    keywords: [study.title, study.subtitle, ...study.tags, "Case Study", "Divyanshu Singh"],
    authors: [{ name: "Divyanshu Singh" }],
    /* og + twitter images are generated by opengraph-image.tsx (per-case themed) */
    openGraph: {
      title,
      description: study.hero.paragraph,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: study.hero.paragraph,
    },
  };
}

export default async function WorkCaseStudyPage({
  params,
}: {
  params: Promise<RouteParams>;
}) {
  const { slug } = await params;
  const study = resolveStudy(slug);
  if (!study) notFound();

  const i = CASE_STUDY_ORDER.indexOf(study.id);
  const next = CASE_STUDIES[CASE_STUDY_ORDER[(i + 1) % CASE_STUDY_ORDER.length]];
  const prev = i > 0 ? CASE_STUDIES[CASE_STUDY_ORDER[i - 1]] : null;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "CreativeWork",
    name: `${study.title} — ${study.subtitle}`,
    headline: `${study.title} — ${study.subtitle}`,
    description: study.hero.paragraph,
    image: study.cover,
    keywords: study.tags.join(", "),
    genre: "UX Design Case Study",
    author: {
      "@type": "Person",
      name: "Divyanshu Singh",
      jobTitle: "Product Designer",
    },
    datePublished: "2026-01-01",
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <CaseStudyPageView study={study} next={next} prev={prev} />
    </>
  );
}
