import type { Note } from "./types";

/**
 * Studio Notes #04 — the pre-ship audit checklist.
 */
export const audit: Note = {
  slug: "the-twenty-minute-audit",
  title: "The 20-minute audit I run before shipping any flow",
  dek: "A compact checklist of states, edges and exits that catches most usability issues before users ever see them.",
  date: "2025-12-15",
  dateLabel: "December 15, 2025",
  dateShort: "Dec 15",
  category: "Process",
  tags: ["process", "QA", "shipping", "checklists"],
  readingMinutes: 4,
  blocks: [
    {
      type: "lead",
      text: "Every flow I ship goes through the same twenty minutes. It is not a formal process — it is a checklist written on a sticky note that has survived three projects, because it keeps catching things no ticket ever mentions. **States before pixels, edges before polish, exits before everything.**",
    },
    { type: "h2", id: "states", text: "States before pixels" },
    {
      type: "p",
      text: "A flow is five screenshots minimum: empty, loading, error, partial, slow. Most teams design one — the happy path, fully populated — and let the other four get generated by whatever the framework does by default. The audit is just walking each state and asking one question: *would a first-time user panic here?*",
    },
    {
      type: "list",
      items: [
        "**Empty** — does it teach, or just occupy space? An empty state that explains *what will appear here* converts dead air into onboarding.",
        "**Loading** — is the skeleton shaped like the content? A spinner on a dashboard screen starts reading as broken after three seconds.",
        "**Error** — does it recover, or just report? Every error message gets exactly one next action.",
        "**Partial** — the underrated one. Half-loaded data, one failed widget in a grid, an offline cache. Partial states are where layouts actually break.",
      ],
    },
    { type: "h2", id: "edges", text: "Edges are where trust leaks" },
    {
      type: "p",
      text: "Then I hunt extremes: the 140-character name, the zero-rupee payment, the timezone-crossing date, the user with a thousand records and the user with none. Edges are cheap to test and expensive to discover in production — every one caught in the audit is a support ticket that never gets filed.",
    },
    {
      type: "callout",
      variant: "tip",
      title: "Keep an edge-case zoo",
      text: "Keep a personal file of every oddity you meet in the wild. After a year you will own the most project-relevant QA checklist in the company — and it will be yours, not a template's.",
    },
    { type: "h2", id: "checklist", text: "The checklist itself" },
    { type: "p", text: "The full sticky note, unabridged:" },
    {
      type: "list",
      ordered: true,
      items: [
        "Every screen has all five states designed, not defaulted.",
        "Every error message names a next action.",
        "Every destructive action is reversible, or confirmed with copy that states the consequence.",
        "Every list has an empty state that teaches.",
        "Every form validates on blur, not on keystroke.",
        "Every fetch over 300 milliseconds shows progress shaped like the result.",
        "Every number has a unit, a trend, and a timestamp.",
        "Every flow works one-handed, thumb-reach, in a moving autorickshaw.",
        "Every dark-mode screen is checked after being designed, not the week before shipping.",
        "Someone who has never seen the flow can complete it while talking to me about something else.",
      ],
    },
    {
      type: "quote",
      text: "The audit takes twenty minutes because that is still shorter than the standup where we would otherwise argue about it.",
      cite: "— written on the back of the sticky note, later",
    },
    {
      type: "p",
      text: "None of this is clever, and that is exactly the point. The audit exists so judgement can be spent on the *product* questions — the narrative, the hierarchy, the trust — instead of the preventable ones.",
    },
  ],
};
