import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NOTES, getNoteNeighbours } from "@/lib/notes";
import { NoteArticleView } from "@/components/portfolio/notes/note-article";

interface RouteParams {
  slug: string;
}

export function generateStaticParams(): RouteParams[] {
  return NOTES.map((n) => ({ slug: n.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<RouteParams>;
}): Promise<Metadata> {
  const { slug } = await params;
  const note = NOTES.find((n) => n.slug === slug);
  if (!note) return {};

  const title = `${note.title} — Studio Notes`;
  return {
    title,
    description: note.dek,
    keywords: [note.category, ...note.tags, "Studio Notes", "Divyanshu Singh"],
    authors: [{ name: "Divyanshu Singh" }],
    /* og + twitter images generated by opengraph-image.tsx (file convention) */
    openGraph: {
      title,
      description: note.dek,
      type: "article",
      publishedTime: note.date,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: note.dek,
    },
  };
}

export default async function NoteArticlePage({
  params,
}: {
  params: Promise<RouteParams>;
}) {
  const { slug } = await params;
  if (!NOTES.some((n) => n.slug === slug)) notFound();

  const { note, newer, older } = getNoteNeighbours(slug);

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: note.title,
    description: note.dek,
    datePublished: note.date,
    articleSection: note.category,
    keywords: note.tags.join(", "),
    wordCount: note.readingMinutes * 210,
    author: {
      "@type": "Person",
      name: "Divyanshu Singh",
      jobTitle: "Product Designer",
    },
    publisher: {
      "@type": "Person",
      name: "Divyanshu Singh",
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `/notes/${note.slug}`,
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <NoteArticleView note={note} newer={newer} older={older} />
    </>
  );
}
